name: release

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  release:
    uses: Gluck-House/7dtd-mod-infra/.github/workflows/reusable-release.yml@main
    secrets: inherit
    with:
      project_name: "TimeLoop"
      artifact_folder: "TimeLoop"
