name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    uses: "Gluck-House/7dtd-mod-infra/.github/workflows/reusable-release-please.yml@main"
    secrets: inherit
